# Generated by Django 4.2.4 on 2023-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oecd", "0002_remove_oecdmodel_t6_year_oecdmodel_t6_periods_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="oecdmodel_t1",
            index=models.Index(fields=["Code"], name="t1_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t2",
            index=models.Index(fields=["Code"], name="t2_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t3",
            index=models.Index(fields=["Code"], name="t3_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t4",
            index=models.Index(fields=["Code"], name="t4_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t5",
            index=models.Index(fields=["Code"], name="t5_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t6",
            index=models.Index(fields=["Code"], name="t6_code_idx"),
        ),
        migrations.AddIndex(
            model_name="oecdmodel_t7",
            index=models.Index(fields=["Code"], name="t7_code_idx"),
        ),
    ]
