# Generated by Django 4.1.8 on 2023-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(help_text='国家', max_length=50, verbose_name='国家')),
                ('Country_Code', models.CharField(help_text='国家代码', max_length=20, verbose_name='国家代码')),
                ('Indicator_Name', models.CharField(help_text='指标', max_length=100, verbose_name='指标')),
                ('Indicator_Code', models.CharField(help_text='指标代码', max_length=50, verbose_name='指标代码')),
                ('year', models.IntegerField(help_text='年份', verbose_name='年份')),
                ('value', models.FloatField(blank=True, help_text='值', null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': 'worldbank',
                'verbose_name_plural': 'worldbank',
                'db_table': 'wb',
            },
        ),
    ]
