# Generated by Django 4.1.8 on 2023-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmodel',
            name='Country_Name',
            field=models.CharField(help_text='国家', max_length=80, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wbmodel',
            name='Indicator_Name',
            field=models.CharField(help_text='指标', max_length=150, verbose_name='指标'),
        ),
    ]
