# Generated by Django 4.1.8 on 2023-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QGModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(help_text='指标', max_length=100, verbose_name='指标')),
                ('code', models.CharField(help_text='代码', max_length=10, verbose_name='代码')),
                ('year', models.IntegerField(help_text='年份', verbose_name='年份')),
                ('value', models.FloatField(help_text='值', verbose_name='值')),
            ],
            options={
                'verbose_name': '全国指标',
                'verbose_name_plural': '全国指标',
                'db_table': 'stats_qg',
            },
        ),
    ]
