# Generated by Django 4.2.4 on 2023-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measure",
                    models.CharField(help_text="指标", max_length=100, verbose_name="指标"),
                ),
                (
                    "mea_code",
                    models.CharField(
                        help_text="指标代码", max_length=8, verbose_name="指标代码"
                    ),
                ),
                (
                    "province",
                    models.CharField(help_text="省份", max_length=20, verbose_name="省份"),
                ),
                (
                    "prov_code",
                    models.CharField(
                        help_text="省份代码", max_length=4, verbose_name="省份代码"
                    ),
                ),
                ("year", models.IntegerField(help_text="年份", verbose_name="年份")),
                ("value", models.FloatField(help_text="值", verbose_name="值")),
            ],
            options={
                "verbose_name": "各省指标",
                "verbose_name_plural": "各省指标",
                "db_table": "stats_gs",
            },
        ),
    ]
