# Generated by Django 4.2.4 on 2023-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_gsmodel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gsmodel",
            index=models.Index(fields=["mea_code"], name="mea_code_idx"),
        ),
        migrations.AddIndex(
            model_name="qgmodel",
            index=models.Index(fields=["code"], name="code_idx"),
        ),
    ]
