# Generated by Django 4.1.8 on 2023-07-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whomodel',
            name='SpatialDimDetail',
            field=models.CharField(blank=True, help_text='空间维度', max_length=40, null=True, verbose_name='空间维度'),
        ),
        migrations.AlterField(
            model_name='whomodel',
            name='SpatialDim',
            field=models.CharField(blank=True, help_text='空间维度代码', max_length=60, null=True, verbose_name='空间维度代码'),
        ),
    ]
