# Generated by Django 4.2.4 on 2023-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GBDModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="标题", max_length=100, verbose_name="标题"),
                ),
                ("data", models.JSONField(help_text="数据", verbose_name="数据")),
            ],
            options={
                "verbose_name": "gbd数据",
                "verbose_name_plural": "gbd数据",
                "db_table": "gbd",
            },
        ),
    ]
