# Generated by Django 4.2.4 on 2023-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gbd", "0002_gbdmodel_parent_alter_gbdmodel_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gbdmodel",
            name="visualizable",
            field=models.BooleanField(
                default=False, help_text="可视化", verbose_name="可视化"
            ),
        ),
    ]
