# Generated by Django 4.2.4 on 2023-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gbd", "0003_gbdmodel_visualizable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gbdmodel",
            index=models.Index(fields=["title", "parent"], name="title_parent_idx"),
        ),
    ]
