# Generated by Django 4.2.4 on 2023-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gbd", "0004_gbdmodel_title_parent_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="gbdmodel",
            name="current_page",
            field=models.IntegerField(
                blank=True, help_text="当前页", null=True, verbose_name="当前页"
            ),
        ),
        migrations.AddField(
            model_name="gbdmodel",
            name="total_page",
            field=models.IntegerField(
                blank=True, help_text="总页数", null=True, verbose_name="总页数"
            ),
        ),
    ]
