# Generated by Django 4.2.4 on 2023-11-21 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gbd", "0005_gbdmodel_current_page_gbdmodel_total_page"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GBDModel",
        ),
    ]
